package payments

import "time"

// Payment Status constants representing the lifecycle state machine.
const (
	StatusPending    = "pending"
	StatusProcessing = "processing"
	StatusSuccessful = "successful"
	StatusFailed     = "failed"
)

// Payment represents a single payment transaction in our domain model.
type Payment struct {
	ID             string    `json:"id"`
	IdempotencyKey string    `json:"idempotency_key"`
	Amount         int64     `json:"amount"` // Always stored in kobo (1 NGN = 100 kobo)
	Currency       string    `json:"currency"`
	Status         string    `json:"status"`
	FailureReason  string    `json:"failure_reason,omitempty"`
	CustomerID     string    `json:"customer_id"`
	MerchantID     string    `json:"merchant_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

// IsTerminal returns true if the payment has reached a final state (successful or failed).
func (p *Payment) IsTerminal() bool {
	return p.Status == StatusSuccessful || p.Status == StatusFailed
}

// CreatePaymentInput is the incoming payload sent by a client to request a payment.
// We keep this separate from Payment because fields like ID, Status, and Timestamps
// are generated by our server, not provided by the caller.
type CreatePaymentInput struct {
	IdempotencyKey string `json:"idempotency_key"`
	Amount         int64  `json:"amount"`
	Currency       string `json:"currency"`
	CustomerID     string `json:"customer_id"`
	MerchantID     string `json:"merchant_id"`
}
