name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-build:
    name: Build & Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Download Go Dependencies
        run: |
          cd services/payments && go mod download

      - name: Run Payments Unit Tests
        run: |
          cd services/payments && go test -v ./...

      - name: Build Payments Service Binary
        run: |
          cd services/payments && go build -v ./cmd/api

      - name: Build Bank Simulator Binary
        run: |
          cd services/bank-simulator && go build -v ./cmd/api
